### ISSUE TITLE
Next and previous track command not working in Spotify SingleRoom mode

### ISSUE THREAD

**Issue by B5r1oJ0A9G** [B5r1oJ0A9G/teufel_raumfeld#49]
allright, now it partly works for me, I don't know what exactly changed, I did a ton of restarting, reinstalling and so on concerning other problems. HA still does not realize if music is playing via spotify multiroom. If I hit play though, it starts playing from the multiroom speaker. Background-image still does not appear, but who cares. What bothers me is that i cant skip or replay songs. Imma just dump the log report here, can't make out what is of relevance and what not

`    [140228859544000] 'HassRaumfeldHost' object has no attribute 'async_room_next_track'

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 193, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1704, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1741, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 680, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 964, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 717, in _handle_entity_call
    await result
  File "/config/custom_components/teufel_raumfeld/media_player.py", line 419, in async_media_next_track
    await self._raumfeld.async_room_next_track(self._room)
AttributeError: 'HassRaumfeldHost' object has no attribute 'async_room_next_track'
`

_Originally posted by @MaxSchuck in https://github.com/B5r1oJ0A9G/teufel_raumfeld/issues/4#issuecomment-1159589792_

**Comment by B5r1oJ0A9G** [comment]
`teufel_raumfeld` is using (currently) incorrect function calls from `hassfeld` for playing next or previous tracks. In fact, the functions are not consistently correct defined in `hassfeld`.

**Comment by B5r1oJ0A9G** [comment]
The function names are corrected now in ``hassfeld`` with its release of version 0.3.11-alpha2. This new version will be used by ``teufel_hassfeld`` in the current master branch.

@MaxSchuck,
@ulilicht,
Please consider to test the current master branch and report back whether the error is fixed.

**Comment by B5r1oJ0A9G** [comment]
Released in  [v0.1.13-alpha1](https://github.com/B5r1oJ0A9G/teufel_raumfeld/releases/tag/v0.1.13-alpha1).
