### ISSUE TITLE
Raumfeld One S cannot be used for playing media from Homeassistant

### ISSUE THREAD

**Issue by chris-nite** [B5r1oJ0A9G/teufel_raumfeld#56]
First off i would like to thank you for your ongoing support of our Teufel and Raumfeld Speakers. Having them integrated into Home Assistant adds great benefit for many use cases, everyone got at home.
Since your recent update i was finally able to play Radio Stations directly on my Raumfeld One S speakers in my home.

**My current setup is:**
-2x Raumfeld One S (the first generation; works perfectly with your integration)
-2x Teufel One S (current gen, won't work with media_player.play-functions)

Unfortunately the current gen Teufel One S-Speakers somehow can not be used to play from Home Assistant.
Whenever i choose a Radio Station through the Selector-Popup inside Home Assistant, the following messages appear in my log:

` Logger: pychromecast.socket_client
Source: /usr/local/lib/python3.11/site-packages/pychromecast/socket_client.py:398
First occurred: 30. Dezember 2023 um 23:29:42 (31 occurrences)
Last logged: 09:12:50
[Schlafzimmer(192.168.120.231):8009] Failed to connect to service ServiceInfo(type='mdns', data='Raumfeld-One-S-c3ac909469cd6a7b7ebedaa4712e1392._googlecast._tcp.local.'), retrying in 5.0s`

`Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:238
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 09:12:44 (5 occurrences)
Last logged: 09:13:39
[140262985549376] None
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 238, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2067, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2104, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 272, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 878, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 948, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/teufel_raumfeld/media_player.py", line 544, in async_play_media
    await self._raumfeld.async_set_av_transport_uri(
  File "/usr/local/lib/python3.11/site-packages/hassfeld/__init__.py", line 767, in async_set_av_transport_uri
    zone_loc = self.resolve["udn_to_devloc"][zone_udn]
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: None`

As far as i know and according to the german support-site of Teufel, it seems that the Teufel WIFI-product line (https://support.teufel.de/hc/de/articles/360001161345-Woran-erkenne-ich-ob-mein-Teufel-Streaming-Raumfeld-Ger%C3%A4t-Chromecast-unterst%C3%BCtzt-) won't support Chromecast anymore...i guess that might be the culprit, am i right?

Nevertheless it seems to be possible to play Webradio-Stations on the Teufel media players directly from the raumfeld-app itself, so there might/must be some way to trigger this, hopefully through home assistant.

I am happy to provide any logs necessary to get to the bottom of it. 
Thank you in advance and best wishes
Chris

**Comment by B5r1oJ0A9G** [comment]
Hello, my setup consists only of Teufel One speaker generations. The integration has even been developed with these. Chromecast is also not used with this integration, as you correctly noted, it is not supported by the speakers. Today the versin 0.1.16-alpha1 incl. some bug fixes was released. Are you still facing this issue with that release?
